import fs from 'node:fs/promises';
import path from 'node:path';
import { logger } from './logger.js';

const ARTIFACTS_DIR = path.resolve(process.cwd(), 'artifacts');
const SCREENSHOTS_DIR = path.join(ARTIFACTS_DIR, 'screenshots');
const TRACES_DIR = path.join(ARTIFACTS_DIR, 'traces');
const VIDEOS_DIR = path.join(ARTIFACTS_DIR, 'videos');
const LOGS_DIR = path.join(ARTIFACTS_DIR, 'logs');
const NETWORK_DIR = path.join(ARTIFACTS_DIR, 'network');

/**
 * Sanitizes a filename or ID to prevent path traversal.
 *
 * @param {string} input - Raw identifier or filename
 * @returns {string} Sanitized string
 */
export function sanitizeFilename(input) {
  if (!input || typeof input !== 'string') return 'artifact';
  return input
    .replace(/\.\.+/g, '__')
    .replace(/[^a-zA-Z0-9_\-\.]/g, '_');
}

/**
 * Verifies that a target file path resolves strictly within the artifacts directory.
 * Prevents directory traversal vulnerabilities.
 *
 * @param {string} targetPath - Path to check
 * @returns {boolean} True if safe
 */
export function isSafeArtifactPath(targetPath) {
  const resolved = path.resolve(targetPath);
  return resolved.startsWith(ARTIFACTS_DIR);
}

/**
 * Ensures all artifact category storage directories exist.
 */
export async function ensureArtifactDirs() {
  const dirs = [
    ARTIFACTS_DIR,
    SCREENSHOTS_DIR,
    TRACES_DIR,
    VIDEOS_DIR,
    LOGS_DIR,
    NETWORK_DIR,
  ];

  for (const dir of dirs) {
    try {
      await fs.mkdir(dir, { recursive: true });
    } catch (err) {
      logger.error(`Failed to create artifact directory [${dir}]:`, err.message);
    }
  }
}

/**
 * Sanitizes sensitive request/response headers before storage.
 *
 * @param {Record<string, string>} [headers={}] - Raw headers
 * @returns {Record<string, string>} Sanitized headers
 */
export function sanitizeNetworkHeaders(headers = {}) {
  if (!headers || typeof headers !== 'object') return {};
  const sensitivePatterns = /^(authorization|cookie|set-cookie|x-api-key|token|secret|password|proxy-authorization)$/i;

  const sanitized = {};
  for (const [key, val] of Object.entries(headers)) {
    if (sensitivePatterns.test(key)) {
      sanitized[key] = '[REDACTED]';
    } else {
      sanitized[key] = val;
    }
  }
  return sanitized;
}

/**
 * Captures a full-page screenshot on test step failure and saves it to the artifacts directory.
 * Returns a client-accessible URL reference without storing binary buffers in MongoDB.
 *
 * @param {import('playwright').Page} page - Active Playwright page
 * @param {string} runId - Current TestRun ID
 * @param {number} stepOrder - Failing step sequence number
 * @returns {Promise<string|null>} Relative URL to screenshot artifact or null
 */
export async function captureFailureScreenshot(page, runId, stepOrder) {
  if (!page) return null;

  try {
    await ensureArtifactDirs();
    const cleanId = sanitizeFilename(runId);
    const filename = `${cleanId}_step_${stepOrder}_${Date.now()}.png`;
    const filepath = path.join(SCREENSHOTS_DIR, filename);

    if (!isSafeArtifactPath(filepath)) {
      throw new Error('Unsafe artifact destination path detected');
    }

    await page.screenshot({
      path: filepath,
      fullPage: true,
      timeout: 5000,
    });

    return `/artifacts/screenshots/${filename}`;
  } catch (err) {
    logger.warn('Failed to capture failure screenshot:', err.message);
    return null;
  }
}

/**
 * Saves a screenshot from page.
 *
 * @param {import('playwright').Page} page
 * @param {string} runId
 * @returns {Promise<string|null>}
 */
export async function saveScreenshot(page, runId) {
  return captureFailureScreenshot(page, runId, 'general');
}

/**
 * Stops Playwright tracing and saves the trace zip file to the artifacts directory.
 *
 * @param {import('playwright').BrowserContext} context - Active browser context
 * @param {string} runId - TestRun ID
 * @returns {Promise<string|null>} Relative URL to trace artifact or null
 */
export async function saveTrace(context, runId) {
  if (!context) return null;

  try {
    await ensureArtifactDirs();
    const cleanId = sanitizeFilename(runId);
    const filename = `${cleanId}_trace.zip`;
    const filepath = path.join(TRACES_DIR, filename);

    if (!isSafeArtifactPath(filepath)) {
      throw new Error('Unsafe trace destination path detected');
    }

    await context.tracing.stop({ path: filepath });
    return `/artifacts/traces/${filename}`;
  } catch (err) {
    logger.warn('Failed to save Playwright trace:', err.message);
    return null;
  }
}

/**
 * Saves/moves a recorded video file to the persistent videos artifact directory.
 *
 * @param {string} sourceVideoPath - Temporary path to video generated by Playwright
 * @param {string} runId - TestRun ID
 * @returns {Promise<string|null>} Relative URL to video artifact or null
 */
export async function saveVideo(sourceVideoPath, runId) {
  if (!sourceVideoPath) return null;

  try {
    await ensureArtifactDirs();
    const cleanId = sanitizeFilename(runId);
    const ext = path.extname(sourceVideoPath) || '.webm';
    const filename = `${cleanId}_video${ext}`;
    const targetPath = path.join(VIDEOS_DIR, filename);

    if (!isSafeArtifactPath(targetPath)) {
      throw new Error('Unsafe video destination path detected');
    }

    await fs.copyFile(sourceVideoPath, targetPath);
    // Attempt cleanup of temp video file
    try {
      await fs.unlink(sourceVideoPath);
    } catch {
      // Ignore cleanup error of temp file
    }

    return `/artifacts/videos/${filename}`;
  } catch (err) {
    logger.warn('Failed to save video artifact:', err.message);
    return null;
  }
}

/**
 * Saves collected console logs to disk as a JSON artifact.
 *
 * @param {Array<object>} consoleLogs - Collected console messages
 * @param {string} runId - TestRun ID
 * @returns {Promise<string|null>} Relative URL to console log artifact or null
 */
export async function saveConsoleLogs(consoleLogs, runId) {
  if (!Array.isArray(consoleLogs) || consoleLogs.length === 0) return null;

  try {
    await ensureArtifactDirs();
    const cleanId = sanitizeFilename(runId);
    const filename = `${cleanId}_console.json`;
    const filepath = path.join(LOGS_DIR, filename);

    if (!isSafeArtifactPath(filepath)) {
      throw new Error('Unsafe console log path detected');
    }

    await fs.writeFile(filepath, JSON.stringify(consoleLogs, null, 2), 'utf-8');
    return `/artifacts/logs/${filename}`;
  } catch (err) {
    logger.warn('Failed to save console log artifact:', err.message);
    return null;
  }
}

/**
 * Saves collected network logs to disk as a sanitized JSON artifact.
 *
 * @param {Array<object>} networkLogs - Collected network transactions
 * @param {string} runId - TestRun ID
 * @returns {Promise<string|null>} Relative URL to network log artifact or null
 */
export async function saveNetworkLog(networkLogs, runId) {
  if (!Array.isArray(networkLogs) || networkLogs.length === 0) return null;

  try {
    await ensureArtifactDirs();
    const cleanId = sanitizeFilename(runId);
    const filename = `${cleanId}_network.json`;
    const filepath = path.join(NETWORK_DIR, filename);

    if (!isSafeArtifactPath(filepath)) {
      throw new Error('Unsafe network log path detected');
    }

    // Sanitize entries before saving
    const sanitized = networkLogs.map((entry) => ({
      ...entry,
      headers: sanitizeNetworkHeaders(entry.headers),
    }));

    await fs.writeFile(filepath, JSON.stringify(sanitized, null, 2), 'utf-8');
    return `/artifacts/network/${filename}`;
  } catch (err) {
    logger.warn('Failed to save network log artifact:', err.message);
    return null;
  }
}
